
experiment:
  type: "imagenet_classification"
  name: "imagenet classification"
  model: "mobilevit_xxs"
  dataset: "imagenet"
  seed: 123

erm:
  n_values: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22] #, 24, 26, 28, 30]
  solutions_per_n: 100 #1000

doc:
  n_trials: 1000000 # 1000000
  histogram_bins: 100

training:
  optimizer: "sgd"
  lr: 0.01
  batch_size: 32
  epochs: 100
  
dataset:
  name: "imagenet"
  test_size: 600
  train_size: 2000
  root_path: "data/ILSVRC2012_img"

dataloader:
  num_workers: 12
  batch_size: 64
  prefetch_factor: 4

models:
  mobilevit_s:
    name: "mobilevit_s"
    num_classes: 2
  mobilevit_xs:
    name: "mobilevit_xs"
    num_classes: 2
  mobilevit_xxs:
    name: "mobilevit_xxs"
    num_classes: 2
  