
experiment:
  type: "mnist_classification"
  name: "mnist Classification"
  model: "mlp1"
  dataset: "gaussian"
  seed: 123

erm:
  n_values: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
  solutions_per_n: 1000 #1000

doc:
  n_trials: 1000000 # 1000000
  histogram_bins: 100

training:
  optimizer: "sgd"
  lr: 0.01
  batch_size: 32
  epochs: 100

plotting:
  save_plots: False
  save_dir: "./results/plots"
  
dataset:
  mnist:
    test_size: 1800
    train_size: 6000
    root: "./data/mnist"
    train_images_filepath: "./data/mnist/train-images-idx3-ubyte" 
    train_labels_filepath: "./data/mnist/train-labels-idx1-ubyte"
    test_images_filepath: "./data/mnist/t10k-images-idx3-ubyte"
    test_labels_filepath: "./data/mnist/t10k-labels-idx1-ubyte"


models:
  mlp1:
    type: "mlp"
    input_dim: 784
    hidden_layers: []
    output_dim: 2
    bias: False
    activation: "leaky_relu"
  mlp2:
    type: "mlp"
    input_dim: 784
    hidden_layers: [10]
    output_dim: 2
    bias: False
    activation: "leaky_relu"
  